### ISSUE TITLE
Patch AX_LIB_ORACLE_OCI macro for plain C

### ISSUE THREAD

**Issue by mloskot** [mloskot/autotools-modules#2]
Patch e-mailed from @maxsatula

1. Normally OCI is a library for C language, whereas C++ programmers would use OCCI instead. Thus, it is more natural to use a C compiler in the macro, rather than C++ what is currently in use. Not a big deal in Linux, however when I use autoconf in non-Linux environment (such as IBM AIX), I basically might not have a C++ compiler at all, and that lack of compiler breaks configuration checks.

2. At least some Linux distributions (Gentoo, Ubuntu) started using `--as-needed` linker flag everywhere. AX_LIB_ORACLE_OCI fails to find libraries if a program is being configured as `./configure LDFLAGS="-Wl,--as-needed"`
Solution is to split LDFLAGS into two variables, LDFLAGS and LIBS.
LDFLAGS contains `-Llibrarydir` only, and LIBS has `-lclntsh`

https://github.com/maxsatula/ocp/blob/develop/m4/ax_lib_oracle_oci.m4.patch

------

Push updated macro to GNU Autoconf Archive at https://savannah.gnu.org/projects/autoconf-archive

**Comment by maxsatula** [comment]
Hi @mloskot,
In the proposed patch, I split linker options to `LDFLAGS` and `LIBS` variables, but then I merge them back to a single `ORACLE_OCI_LDFLAGS` to preserve an old interface compatible with existing programs which use the macro. Maybe it is not a good approach, and needs to further split to `ORACLE_OCI_LDFLAGS` and `ORACLE_OCI_LIBS` in the future.

Also, not sure if `AC_LANG_PUSH([C])` and `AC_LANG_POP([C])` lines are needed at all. I left them just being extra cautious, but apparently C is a default language already, on the other hand a user may choose some wrong language in their `configure.ac` and we need to make sure we use C. Not sure here.

**Comment by maxsatula** [comment]
3. I had to replace C++ style comments `//` with C style `/* ... */`, otherwise old C compilers might fail to recognize them

**Comment by mloskot** [comment]
@maxsatula Thanks for the explanation.

Wuold you care to submit the patch as pull request, so your commit/credit is properly preserved?

**Comment by maxsatula** [comment]
@mloskot,
It has been merged to upstream. Thank you! To close, I guess.

**Comment by mloskot** [comment]
Great, thanks
